### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by bingzhuan** [arhiLAZAR/ldap-to-elastic#1]
Could someone  tell me how to slove it ?

> arhilazar/ldap-to-elastic
Traceback (most recent call last):
  File "/app/ldap_to_elastic.py", line 243, in <module>
    main()
  File "/app/ldap_to_elastic.py", line 227, in main
    ldapUsers = getLdapUsers()
  File "/app/ldap_to_elastic.py", line 81, in getLdapUsers
    if ldapGroupsListKey in user[1].keys():
AttributeError: 'list' object has no attribute 'keys'

**Comment by arhiLAZAR** [comment]
Hi, @bingzhuan 

I assume this error is caused by some different format of an LDAP response.
I've added an additional check to prevent it, but probably the script won't work as expected with these unpredicted formats.

Could you pull the latest version of the docker image and run it with the additional environment variable **L2E_DEBUG** set to "true"
```--env L2E_DEBUG=true```
and then post here the part of the output right after the line "**Got some unpredicted response from LDAP:**"?

Or, if it's appropriate, run with 
```--env L2E_DEBUG=verbose```
and share the "**Full LDAP response:**" from the output?
